version: '2'
services:
  load-balancer:
    ports:
    - 80:80
    image: rancher/lb-service-haproxy:v0.5.9
    labels:
      io.rancher.scheduler.affinity:host_label: master=1
      io.rancher.container.network: true 
  reverse-proxy:
    environment:
      RANCHER_HOST: ${RANCHER_HOST}
      RANCHER_ACCESS_KEY: ${RANCHER_ACCESS_KEY}
      RANCHER_SECRET_KEY: ${RANCHER_SECRET_KEY}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.network: true 
      io.rancher.scheduler.affinity:host_label: master=1
    tty: true
    image: krack/rancher-proxy:latest
    stdin_open: true
  load-balancer-https:
    ports:
    - 443:443
    image: nginx:mainline-alpine
    volumes:
    - nginx-certs:/etc/nginx/certs:ro
    - /opt/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    labels:
    io.rancher.scheduler.affinity:host_label: master=1
    io.rancher.container.network: true
