version: '2'
services:
  load-balancer:
    ports:
    - 80
    image: rancher/lb-service-haproxy:v0.4.6
  reverse-proxy:
    environment:
      RANCHER_URL: ${RANCHER_URL}
      RANCHER_ACCESS_KEY: ${RANCHER_ACCESS_KEY}
      RANCHER_SECRET_KEY: ${RANCHER_SECRET_KEY}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: master=1
    tty: true
    image: krack/rancher-proxy:test
    stdin_open: true
