new-reverse-proxy:
  ports:
  - 8090:80/tcp
  environment:
    RANCHER_HOST: ${RANCHER_HOST}
    RANCHER_ACCESS_KEY: ${RANCHER_ACCESS_KEY}
    RANCHER_SECRET_KEY: ${RANCHER_SECRET_KEY}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: krack/rancher-proxy:test
  stdin_open: true
reverse-proxy:
  ports:
  - 80:80/tcp
  labels:
    io.rancher.container.pull_image: always
  image: krack/rancher-proxy:latest